// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListNamespaces(arg1:string):Promise<Array<any>>;

export function ListPods(arg1:string):Promise<Array<any>>;

export function StartNamespaceSync(arg1:string):Promise<void>;

export function StartPodSync(arg1:string):Promise<void>;

export function StopNamespaceSync(arg1:string):Promise<void>;

export function StopPodSync(arg1:string):Promise<void>;
