// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetKnownResources(arg1) {
  return window['go']['pkg']['App']['GetKnownResources'](arg1);
}

export function GetVersion(arg1) {
  return window['go']['pkg']['App']['GetVersion'](arg1);
}

export function ListCronJobs(arg1) {
  return window['go']['pkg']['App']['ListCronJobs'](arg1);
}

export function ListDaemonSets(arg1) {
  return window['go']['pkg']['App']['ListDaemonSets'](arg1);
}

export function ListDeployments(arg1) {
  return window['go']['pkg']['App']['ListDeployments'](arg1);
}

export function ListJobs(arg1) {
  return window['go']['pkg']['App']['ListJobs'](arg1);
}

export function ListNamespaces(arg1) {
  return window['go']['pkg']['App']['ListNamespaces'](arg1);
}

export function ListPods(arg1) {
  return window['go']['pkg']['App']['ListPods'](arg1);
}

export function ListReplicaSets(arg1) {
  return window['go']['pkg']['App']['ListReplicaSets'](arg1);
}

export function ListStatefulSets(arg1) {
  return window['go']['pkg']['App']['ListStatefulSets'](arg1);
}

export function ReadKubeConfigs() {
  return window['go']['pkg']['App']['ReadKubeConfigs']();
}

export function StartCronJobSync(arg1) {
  return window['go']['pkg']['App']['StartCronJobSync'](arg1);
}

export function StartDaemonSetsSync(arg1) {
  return window['go']['pkg']['App']['StartDaemonSetsSync'](arg1);
}

export function StartDeploymentsSync(arg1) {
  return window['go']['pkg']['App']['StartDeploymentsSync'](arg1);
}

export function StartJobSync(arg1) {
  return window['go']['pkg']['App']['StartJobSync'](arg1);
}

export function StartNamespaceSync(arg1) {
  return window['go']['pkg']['App']['StartNamespaceSync'](arg1);
}

export function StartPodSync(arg1) {
  return window['go']['pkg']['App']['StartPodSync'](arg1);
}

export function StartReplicaSetsSync(arg1) {
  return window['go']['pkg']['App']['StartReplicaSetsSync'](arg1);
}

export function StartStatefulSetsSync(arg1) {
  return window['go']['pkg']['App']['StartStatefulSetsSync'](arg1);
}

export function StopCronJobSync(arg1) {
  return window['go']['pkg']['App']['StopCronJobSync'](arg1);
}

export function StopDaemonSetsSync(arg1) {
  return window['go']['pkg']['App']['StopDaemonSetsSync'](arg1);
}

export function StopDeploymentsSync(arg1) {
  return window['go']['pkg']['App']['StopDeploymentsSync'](arg1);
}

export function StopJobSync(arg1) {
  return window['go']['pkg']['App']['StopJobSync'](arg1);
}

export function StopNamespaceSync(arg1) {
  return window['go']['pkg']['App']['StopNamespaceSync'](arg1);
}

export function StopPodSync(arg1) {
  return window['go']['pkg']['App']['StopPodSync'](arg1);
}

export function StopReplicaSetsSync(arg1) {
  return window['go']['pkg']['App']['StopReplicaSetsSync'](arg1);
}

export function StopStatefulSetsSync(arg1) {
  return window['go']['pkg']['App']['StopStatefulSetsSync'](arg1);
}
