// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pkg} from '../models';

export function GetKnownResources(arg1:string):Promise<Array<pkg.Resource>>;

export function GetVersion(arg1:string):Promise<string>;

export function ListCronJobs(arg1:string):Promise<Array<any>>;

export function ListDaemonSets(arg1:string):Promise<Array<any>>;

export function ListDeployments(arg1:string):Promise<Array<any>>;

export function ListJobs(arg1:string):Promise<Array<any>>;

export function ListNamespaces(arg1:string):Promise<Array<any>>;

export function ListPods(arg1:string):Promise<Array<any>>;

export function ListReplicaSets(arg1:string):Promise<Array<any>>;

export function ListStatefulSets(arg1:string):Promise<Array<any>>;

export function ReadKubeConfigs():Promise<Array<pkg.BosunCluster>>;

export function StartCronJobSync(arg1:string):Promise<void>;

export function StartDaemonSetsSync(arg1:string):Promise<void>;

export function StartDeploymentsSync(arg1:string):Promise<void>;

export function StartJobSync(arg1:string):Promise<void>;

export function StartNamespaceSync(arg1:string):Promise<void>;

export function StartPodSync(arg1:string):Promise<void>;

export function StartReplicaSetsSync(arg1:string):Promise<void>;

export function StartStatefulSetsSync(arg1:string):Promise<void>;

export function StopCronJobSync(arg1:string):Promise<void>;

export function StopDaemonSetsSync(arg1:string):Promise<void>;

export function StopDeploymentsSync(arg1:string):Promise<void>;

export function StopJobSync(arg1:string):Promise<void>;

export function StopNamespaceSync(arg1:string):Promise<void>;

export function StopPodSync(arg1:string):Promise<void>;

export function StopReplicaSetsSync(arg1:string):Promise<void>;

export function StopStatefulSetsSync(arg1:string):Promise<void>;
