// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListNamespaces(arg1) {
  return window['go']['pkg']['App']['ListNamespaces'](arg1);
}

export function ListPods(arg1) {
  return window['go']['pkg']['App']['ListPods'](arg1);
}

export function StartNamespaceSync(arg1) {
  return window['go']['pkg']['App']['StartNamespaceSync'](arg1);
}

export function StartPodSync(arg1) {
  return window['go']['pkg']['App']['StartPodSync'](arg1);
}

export function StopNamespaceSync(arg1) {
  return window['go']['pkg']['App']['StopNamespaceSync'](arg1);
}

export function StopPodSync(arg1) {
  return window['go']['pkg']['App']['StopPodSync'](arg1);
}
